// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeMgcrU9OjEkZehiMl0TohUmEST4WNJ1M',
    appId: '1:885101643400:web:6ab3c66de4acbb3916813d',
    messagingSenderId: '885101643400',
    projectId: 'npapp-693cb',
    authDomain: 'npapp-693cb.firebaseapp.com',
    storageBucket: 'npapp-693cb.firebasestorage.app',
    measurementId: 'G-9D7DWLLXRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6uL0xNxHCx62h7W-kTMUG7qhfo3O15Y',
    appId: '1:885101643400:android:67ede2efe8dcc39616813d',
    messagingSenderId: '885101643400',
    projectId: 'npapp-693cb',
    storageBucket: 'npapp-693cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RC3pahjQJCBpm44vQefuUgoBQlPNhxY',
    appId: '1:885101643400:ios:c8ff95f79e8a7afe16813d',
    messagingSenderId: '885101643400',
    projectId: 'npapp-693cb',
    storageBucket: 'npapp-693cb.firebasestorage.app',
    iosBundleId: 'com.example.npapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RC3pahjQJCBpm44vQefuUgoBQlPNhxY',
    appId: '1:885101643400:ios:c8ff95f79e8a7afe16813d',
    messagingSenderId: '885101643400',
    projectId: 'npapp-693cb',
    storageBucket: 'npapp-693cb.firebasestorage.app',
    iosBundleId: 'com.example.npapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeMgcrU9OjEkZehiMl0TohUmEST4WNJ1M',
    appId: '1:885101643400:web:29e703b727911bed16813d',
    messagingSenderId: '885101643400',
    projectId: 'npapp-693cb',
    authDomain: 'npapp-693cb.firebaseapp.com',
    storageBucket: 'npapp-693cb.firebasestorage.app',
    measurementId: 'G-M3D805CX4H',
  );
}
